version: "3.5"
services:
  composer:
    image: composer:2.0.7
    container_name: scoreboard_api_composer
    working_dir: /scoreboard-api
    networks:
      - scoreboard_local
    command: install
    volumes:
      - .:/scoreboard-api
  php_fpm:
    build: .
    container_name: scoreboard_api_fpm
    working_dir: /scoreboard-api
    networks:
      - scoreboard_local
    volumes:
      - .:/scoreboard-api
  nginx:
    image: nginx:1.18.0
    container_name: scoreboard_api_nginx
    working_dir: /scoreboard-api
    networks:
      - scoreboard_local
    ports:
      - "8888:80"
    links:
      - php_fpm
      - composer
    volumes:
      - .:/scoreboard-api
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  scoreboard_local: